### ISSUE TITLE
How are the languages published to maven central?

### ISSUE THREAD

**Issue by AntonPieper** [AndroidIDEOfficial/android-tree-sitter#20]
More generally, how can I add another Tree-sitter grammar? Specifically I want to use GLSL. I see that you have forks of tree-sitter-java and the like, but there does not seem to be the source of the maven module. So how can I add my own grammar? Ideally without using maven

**Comment by itsaky** [comment]
The Gradle modules for the grammars are almost identical (just some minor differences in CMakeLists and the Java binding class). Therefore,

- Gradle modules for the grammars are automatically generated by the [`DynamicModulePlugin`](https://github.com/AndroidIDEOfficial/android-tree-sitter/tree/dev/build-logic/ats/src/main/java/com/itsaky/androidide/treesitter/DynamicModulePlugin.kt) using the [`grammars.json`](https://github.com/AndroidIDEOfficial/android-tree-sitter/tree/dev/grammars/grammars.json) file ([learn more](https://github.com/AndroidIDEOfficial/android-tree-sitter/blob/dev/grammars/README.md)).
- There are [other Gradle plugins](https://github.com/AndroidIDEOfficial/android-tree-sitter/tree/dev/build-logic/ats/src/main/java/com/itsaky/androidide/treesitter) that are used to configure/build the grammars.
- Common module configuration for the grammars can be found in [`build.gradle.kts`](https://github.com/AndroidIDEOfficial/android-tree-sitter/blob/52cc0400feee5079cac25b27d1e7b673ee53f436/build.gradle.kts#L136).

The generated modules are located in `rootDir/build/grammar-modules` directory.

To add a new grammar :

1. Add the grammar source to the `grammars` directory. You can add a submodule with the following command :
```bash
git submodule add <remote_url> grammars/<language_name>
```
2. The `language_name` must be the simple name of the language (i.e without the `tree-sitter-` prefix). This name is used to generate the shared library and the Gradle module. For example, if the `language_name` is `abc` :
    - Module `tree-sitter-abc` will be generated.
    - The name of the generated shared library will be `libtree-sitter-abc.so`.
3. Update the `grammars.json` file to include the newly added grammar.
4. Sync the project to generate the module for the grammar.

Also, make sure you read the [prerequisites](https://github.com/AndroidIDEOfficial/android-tree-sitter#prerequisites) for building the project.

**Comment by itsaky** [comment]
The README has been updated to include information about [using/loading external grammars](https://github.com/AndroidIDEOfficial/android-tree-sitter#loading-external-grammars) i.e. grammars that are not published to Maven Central along with this project.
