### ISSUE TITLE
[Feature Request]: add predicates support

### ISSUE THREAD

**Issue by AntonPieper** [AndroidIDEOfficial/android-tree-sitter#23]
I am trying to port the rust bindings for the [`Query` including predicates](https://github.com/tree-sitter/tree-sitter/blob/d0029a15273e526925a764033e9b7f18f96a7ce5/lib/binding_rust/lib.rs#L1372-L1685)) to kotlin. Whilst doing this I noticed that not all functions have bindings.

## What is missing:
 - [x] [`ts_query_capture_quantifier_for_id`](https://github.com/tree-sitter/tree-sitter/blob/d0029a15273e526925a764033e9b7f18f96a7ce5/lib/include/tree_sitter/api.h#L813)
   - Add a [`TSQuantifier`](https://github.com/tree-sitter/tree-sitter/blob/d0029a15273e526925a764033e9b7f18f96a7ce5/lib/include/tree_sitter/api.h#L109-L115)-enum
   - Add a method `TSQuery#getCaptureQuantifierForId(int patternId, int captureId)`

### `getCaptureQuantifierForId` (untested)
**TSQuantifier.java**
```java
public enum TSQuantifier {
  TSQuantifierZero, // must match the array initialization value
  TSQuantifierZeroOrOne,
  TSQuantifierZeroOrMore,
  TSQuantifierOne,
  TSQuantifierOneOrMore
}
```

**TSQuery.java**
```java
public class TSQuery {
  // ...
  public TSQuantifier getCaptureQuantifierForId(int patternId, int captureId) {
    checkAccess();
    int value = Native.getCaptureQuantifierForId(this.pointer, patternId, captureId);
    if (value >= TSQualifier.values().length) throw new IllegalStateException("Illegal TSQuantifier value: " + value);
    return TSQuantifier.values()[value];
  }
  // ...
  private static class Native {
    // ...
    public static native int getCaptureQuantifierForId(long query, int patternId, int captureId);
  }
}
```

**ts_query.cc**
```cc
extern "C" JNIEXPORT jint JNICALL
Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_getCaptureQuantifierForId(JNIEnv* env, jclass self, jlong query, jint patternId, jint captureId) {
  return (jint)ts_query_capture_quantifier_for_id((TSQuery*)query, patternId, captureId);
}
```

**Comment by itsaky** [comment]
Sure, I'll add it. Are there any other APIs you want me to implement?

**Comment by AntonPieper** [comment]
I already have the constructor for `Query` down. Later I'll try to implement the missing methods. For now the only missing function is the `TSQualifier`s. When this works out, `Query` could be used to implement syntax highlighting for all tree-sitter grammars using the `queries/` directory. As is now, `TSQuery` is a wrapper around the API and `TSQuery` [does not directly support predicates like #match?](https://tree-sitter.github.io/tree-sitter/using-parsers#:~:text=not%20handled%20directly%20by%20the%20Tree%2Dsitter%20C%20library.)

**Comment by itsaky** [comment]
> As is now, TSQuery is a wrapper around the API and TSQuery does not directly support predicates like #match?

As written in the tree-sitter docs, predicates are not directly handled by the tree sitter library and as android-tree-sitter only provides Java bindings for the library, I think it will be better if the code editor implementation handles predicates.

You can have a look at [sora-editor](https://github.com/Rosemoe/sora-editor). It supports tree sitter syntax highlighting and has [support for predicates](https://github.com/Rosemoe/sora-editor/tree/main/language-treesitter/src/main/java/io/github/rosemoe/sora/editor/ts/predicate). You can even add your own predicates ([example](https://github.com/AndroidIDEOfficial/AndroidIDE/tree/dev/editor/src/main/java/com/itsaky/androidide/editor/language/treesitter/predicates)).

**Comment by itsaky** [comment]
Added in 5c61cff482532b348e694ddae36e832fd3fe4150. A new release will be published soon.
