### ISSUE TITLE
Treesitter-Java does not support Chinese identifiers

### ISSUE THREAD

**Issue by ZeroAicy** [AndroidIDEOfficial/android-tree-sitter#63]
Java with Chinese identifiers may encounter parsing errors

`//https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-IdentifierChars`
    `identifier: $ => /[\p{L}_$][\p{L}\p{Nd}\u00A2_$]*/,`

Did you not handle Unicode characters that Java can support

**Comment by ZeroAicy** [comment]
identifier: _ => /[\p{XID_Start}_$][\p{XID_Continue}\u00A2_$]*/,
？？？

**Comment by itsaky** [comment]
Report this in tree-sitter-java.
