### ISSUE TITLE
No implementation found for long

### ISSUE THREAD

**Issue by YaoZanFeng** [AndroidIDEOfficial/android-tree-sitter#64]
java.lang.UnsatisfiedLinkError: No implementation found for long com.itsaky.androidide.treesitter.TSQuery$Native.newQuery(com.itsaky.androidide.treesitter.TSQuery, long, java.lang.String) (tried Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_newQuery and Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_newQuery__Lcom_itsaky_androidide_treesitter_TSQuery_2JLjava_lang_String_2

**Comment by itsaky** [comment]
You need to call `TreeSitter.loadLibrary()` to load the native library. Reopen this issue if you did call the mentioned function and the issue still persists.
